/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package shop.management;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author ASUS
 */
public class house extends javax.swing.JFrame {

    /**
     * Creates new form house
     */
    public house() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        tvbuy = new javax.swing.JButton();
        lbuy = new javax.swing.JButton();
        fbuy = new javax.swing.JButton();
        fquantity = new javax.swing.JTextField();
        lquantity = new javax.swing.JTextField();
        tvquantity = new javax.swing.JTextField();
        tvprice = new javax.swing.JLabel();
        lprice = new javax.swing.JLabel();
        fprice = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        fcode = new javax.swing.JComboBox<>();
        lcode = new javax.swing.JComboBox<>();
        tvcode = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("House");

        jButton4.setText("Back");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        tvbuy.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        tvbuy.setText("Buy");
        tvbuy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tvbuyActionPerformed(evt);
            }
        });

        lbuy.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lbuy.setText("Buy");
        lbuy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lbuyActionPerformed(evt);
            }
        });

        fbuy.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        fbuy.setText("Buy");
        fbuy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fbuyActionPerformed(evt);
            }
        });

        fquantity.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        fquantity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fquantityActionPerformed(evt);
            }
        });

        lquantity.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lquantity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lquantityActionPerformed(evt);
            }
        });

        tvquantity.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        tvquantity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tvquantityActionPerformed(evt);
            }
        });

        tvprice.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        tvprice.setForeground(new java.awt.Color(255, 255, 255));
        tvprice.setText("40000");

        lprice.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lprice.setForeground(new java.awt.Color(255, 255, 255));
        lprice.setText("500");

        fprice.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        fprice.setForeground(new java.awt.Color(255, 255, 255));
        fprice.setText("2500");

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Price");

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Quantity");

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Code");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("TV");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Light");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Fan");

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Item");

        fcode.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "F-01", "F-02", "F-03" }));

        lcode.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "L-01", "L-02", "L-03" }));

        tvcode.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "TV-01", "TV-02", "TV-03" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(fquantity, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lquantity, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(tvquantity, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(100, 100, 100)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbuy)
                                    .addComponent(fbuy)
                                    .addComponent(tvbuy))
                                .addGap(56, 56, 56))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel11)
                                            .addComponent(jLabel7))
                                        .addGap(27, 27, 27)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(tvcode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel17)
                                                    .addComponent(fcode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(lcode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(56, 56, 56)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(lprice)
                                                    .addComponent(fprice)
                                                    .addComponent(tvprice)
                                                    .addComponent(jLabel16)))))
                                    .addComponent(jLabel18))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                                .addComponent(jLabel15)
                                .addGap(204, 204, 204))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(286, 286, 286)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap(6, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(265, 265, 265)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(jLabel17)
                    .addComponent(jLabel16)
                    .addComponent(jLabel15))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(fprice)
                    .addComponent(fquantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fbuy)
                    .addComponent(fcode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(lprice)
                    .addComponent(lquantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbuy)
                    .addComponent(lcode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(tvprice)
                    .addComponent(tvquantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tvbuy)
                    .addComponent(tvcode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(69, 69, 69)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(107, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(729, 608));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        home hm = new home();
        hm.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void tvbuyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tvbuyActionPerformed
       String tvc = String.valueOf(tvcode.getSelectedItem());
        String tvp = tvprice.getText();
        String tvq = tvquantity.getText();
        if(tvc.isEmpty() || tvp.isEmpty() || tvq.isEmpty()){
             JOptionPane.showMessageDialog(this, "Fill up the form properly.", 
                     "Error", JOptionPane.ERROR_MESSAGE);
        }else{

             Connection dbcon = DBconnect.connectDB();

            try {
                PreparedStatement st = (PreparedStatement)
                dbcon.prepareStatement("INSERT INTO tv (tvcode,tvprice,tvquantity) VALUES(?,?,?)");



            st.setString(1, tvc);
            st.setString(2, tvp);
            st.setString(3, tvq);





            int rs = st.executeUpdate();



            JOptionPane.showMessageDialog(this, "Buy Successful.", 
                    "Success", JOptionPane.INFORMATION_MESSAGE);

               dispose();
               Payment hm = new Payment();
               hm.setVisible(true);

            } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Fill up the form properly.", 
                     "Error", JOptionPane.ERROR_MESSAGE);

            tvprice.setText("");
            tvprice.requestFocus();
            tvcode.setSelectedItem("");
            tvquantity.setText("");

        }

        }
    }//GEN-LAST:event_tvbuyActionPerformed

    private void lbuyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lbuyActionPerformed
       String lc = String.valueOf(lcode.getSelectedItem());
        String lp = lprice.getText();
        String lq = lquantity.getText();
        if(lc.isEmpty() || lp.isEmpty() || lq.isEmpty()){
             JOptionPane.showMessageDialog(this, "Fill up the form properly.", 
                     "Error", JOptionPane.ERROR_MESSAGE);
        }else{

             Connection dbcon = DBconnect.connectDB();

            try {
                PreparedStatement st = (PreparedStatement)
                dbcon.prepareStatement("INSERT INTO light (lcode,lprice,lquantity) VALUES(?,?,?)");



            st.setString(1, lc);
            st.setString(2, lp);
            st.setString(3, lq);





            int rs = st.executeUpdate();



            JOptionPane.showMessageDialog(this, "Buy Successful.", 
                    "Success", JOptionPane.INFORMATION_MESSAGE);

               dispose();
               Payment hm = new Payment();
               hm.setVisible(true);

            } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Fill up the form properly.", 
                     "Error", JOptionPane.ERROR_MESSAGE);

            lprice.setText("");
            lprice.requestFocus();
            lcode.setSelectedItem("");
            lquantity.setText("");

        }

        }
    }//GEN-LAST:event_lbuyActionPerformed

    private void fbuyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fbuyActionPerformed
         String fc = String.valueOf(fcode.getSelectedItem());
        String fp = fprice.getText();
        String fq = fquantity.getText();
        if(fc.isEmpty() || fp.isEmpty() || fq.isEmpty()){
             JOptionPane.showMessageDialog(this, "Fill up the form properly.", 
                     "Error", JOptionPane.ERROR_MESSAGE);
        }else{

             Connection dbcon = DBconnect.connectDB();

            try {
                PreparedStatement st = (PreparedStatement)
                dbcon.prepareStatement("INSERT INTO fan (fcode,fprice,fquantity) VALUES(?,?,?)");



            st.setString(1, fc);
            st.setString(2, fp);
            st.setString(3, fq);





            int rs = st.executeUpdate();



            JOptionPane.showMessageDialog(this, "Buy Successful.", 
                    "Success", JOptionPane.INFORMATION_MESSAGE);

               dispose();
               Payment hm = new Payment();
               hm.setVisible(true);

            } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Fill up the form properly.", 
                     "Error", JOptionPane.ERROR_MESSAGE);

            fprice.setText("");
            fprice.requestFocus();
            fcode.setSelectedItem("");
            fquantity.setText("");

        }

        }
    }//GEN-LAST:event_fbuyActionPerformed

    private void fquantityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fquantityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fquantityActionPerformed

    private void lquantityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lquantityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lquantityActionPerformed

    private void tvquantityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tvquantityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tvquantityActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(house.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(house.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(house.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(house.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new house().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton fbuy;
    private javax.swing.JComboBox<String> fcode;
    private javax.swing.JLabel fprice;
    private javax.swing.JTextField fquantity;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton lbuy;
    private javax.swing.JComboBox<String> lcode;
    private javax.swing.JLabel lprice;
    private javax.swing.JTextField lquantity;
    private javax.swing.JButton tvbuy;
    private javax.swing.JComboBox<String> tvcode;
    private javax.swing.JLabel tvprice;
    private javax.swing.JTextField tvquantity;
    // End of variables declaration//GEN-END:variables
}
